networks:

  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

volumes:
    qgroundcontrol_config:
    ignition_config:

services:

  # gazebo ignition (simulator)
  sim:
    container_name: sim
    hostname: sim
    image: jgoppert/auav_f22_sim:latest
    command: ign gazebo -r --render-engine ogre2 /usr/share/mavlink_sitl_ign_gazebo/worlds/iris.world --gui-config /home/docker/.ignition/gazebo/6/gui.config 
    build:
      dockerfile: dockerfiles/sim 
    environment:
      - DISPLAY=:1
      - IGN_GAZEBO_SYSTEM_PLUGIN_PATH=/usr/lib
      - IGN_GAZEBO_RESOURCE_PATH=/usr/share/mavlink_sitl_ign_gazebo/models
      - PX4_HOME_LAT=40.41537099446224
      - PX4_HOME_LON=-86.93289541090424
      - PX4_HOME_ALT=185
      - PX4_SIM_SPEED_FACTOR=1.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ignition_config:/home/docker/.ignition
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  # px4 (autopilot)
  px4:
    container_name: px4
    hostname: px4
    image: jgoppert/auav_f22_px4:latest
    command: terminator --geometry=800x500+0+500 -e "px4_build.sh && px4_start.sh"
    build:
      dockerfile: dockerfiles/px4
    environment:
      - PX4_SIM_HOSTNAME=sim
      - PX4_ONBOARD_HOSTNAME=onboard
      - PX4_GCS_HOSTNAME=172.16.238.13
      - DISPLAY=:1
      - PX4_SIM_MODEL=iris
      - BUILD_PX4=y
    volumes:
      # pass through for X11
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      # mount .git readwrite for development
      - ./.git:/home/docker/.git:rw
      # mount source readwrite for development
      - ./PX4-Autopilot:/home/docker/PX4-Autopilot:rw
      # mount scripts directory read only for development
      - ./px4_scripts/:/home/docker/bin:ro
    networks:
      app_net:
        ipv4_address: 172.16.238.11

  # onboard computer
  onboard:
    container_name: onboard
    hostname: onboard
    image: jgoppert/auav_f22_onboard:latest
    command: terminator --geometry=800x500+0+0 -e "MicroXRCEAgent udp4 -p 15555"
    build:
      dockerfile: dockerfiles/onboard
    environment:
      - DISPLAY=:1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $PWD/ws:/home/docker/ws:rw
    networks:
      app_net:
        ipv4_address: 172.16.238.12

  # ground control station
  gcs:
    container_name: gcs
    hostname: gcs
    image: jgoppert/auav_f22_gcs:latest
    command: ./QGroundControl.AppImage
    build:
      dockerfile: dockerfiles/gcs
    privileged: true
    environment:
      - DISPLAY=:1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - qgroundcontrol_config:/home/docker/.config/QGroundControl.org
    networks:
      app_net:
        ipv4_address: 172.16.238.13

#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=4 : 
